name: Perlmutter
on:
  push:

jobs:
  build:
    runs-on: self-hosted

    steps:

    - name: checkout omega_h
      uses: actions/checkout@v4
      with:
        path: omega_h

    - name: install globus
      run: |
          python -m ensurepip --upgrade --user
          python -m pip install globus-compute-endpoint

    - name: run tests
      working-directory: omega_h/.github/workflows
      run: ls

    