name: Perlmutter
on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        compiler: [g++]
        mpi: [on]

    steps:

    - name: install mpich
      if: ${{ matrix.mpi == 'on' }}
      run: |
           sudo apt update
           sudo apt install mpich
