name: Perlmutter
on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        compiler: [g++]

    steps:

    - uses: actions/checkout@v4
    
    - name: install globus
      run: pip install globus-compute-sdk

    - name: setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: run python
      run: python -c "
        import sys; 
        print(sys.version)"
    
