name: Perlmutter
on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        compiler: [g++]

    steps:

    - name: install globus
      run: pip install globus-compute-sdk
