name: Perlmutter 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
        matrix:
          compiler: [g++]

    - name: install mpich
        run: |
            sudo apt update
            sudo apt install mpich