name: Perlmutter
on:
  push:

jobs:
  build:
    runs-on: self-hosted

    steps:

    - uses: actions/checkout@v4

    - name: checkout omega_h
      uses: actions/checkout@v4
      with:
        path: omega_h

    - name: test dir
      run: pwd